### ISSUE TITLE
pypi package is missing parts of the testsuite

### ISSUE THREAD

**Issue by jlec** [box/genty#42]
running ```python setup.py test```files with

```python
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    main()
  File "setup.py", line 46, in main
    tests_require=test_requirements,
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 146, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 127, in with_project_on_sys_path
    func()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 167, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib64/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.4/unittest/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/usr/lib64/python3.4/test/bad_coding2.py", line 0
SyntaxError: encoding problem: utf8 with BOM
```

**Comment by potrebic** [comment]
Hi and thanks for using gently!

I can't reproduce your issue. It looks like you are using python 3.3. So I tried the following:

```
$ mkvirtualenv --python=/usr/local/bin/python3.3 genty33
$ pip install -r requirements-dev.txt
$ python setup.py test
```

And that worked fine. It ran all ~90 unit tests in genty.

**Comment by jlec** [comment]
different box, same setup I see 
```python
running build_ext
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    main()
  File "setup.py", line 46, in main
    tests_require=test_requirements,
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 146, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 127, in with_project_on_sys_path
    func()
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 167, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib64/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib64/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib64/python3.4/site-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.4/unittest/loader.py", line 105, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/usr/lib64/python3.4/test/win_console_handler.py", line 11, in <module>
    from ctypes import wintypes, WINFUNCTYPE
  File "/usr/lib64/python3.4/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
 * ERROR: dev-python/genty-1.2.1::gentoo failed (test phase):
```
BTW, same behavior with python 2.7-3.5

**Comment by jlec** [comment]
The tarball on pypi is missing test/__init__.py and test/base_test_case.py

**Comment by jmoldow** [comment]
> pypi package is missing parts of the testsuite

This is not a bug. We only package and upload the library itself. See https://github.com/box/genty/blob/master/setup.py#L44

Your stacktraces do not not represent bugs in genty. Either your cloned the repo but didn't cd into it, or you got the source from PyPI (which intentionally doesn't have the test directory). ``setup.py test`` tries to run the ``test_suite`` (which is 'test'), but since our `test` module isn't in your python path, CPython's `test` module is being found instead (leading to bad results).

**Comment by jlec** [comment]
It has the test suite, at least part of it and it would be great if you could ship it completely.

```
genty-1.2.1 $ (130) ll test/
total 40K
-rw-r--r-- 1 justin justin 3.0K Apr  9  2015 test_example.py
-rw-r--r-- 1 justin justin 2.3K Sep  5  2014 test_genty_args.py
-rw-r--r-- 1 justin justin 5.6K Apr  9  2015 test_genty_dataset.py
-rw-r--r-- 1 justin justin  19K Apr  9  2015 test_genty.py
-rw-r--r-- 1 justin justin 1.2K Sep  5  2014 test_genty_repeat.py
```

I am packaging for downstream distro and we all like to test it during installation. So please include the whole testsuite in the pypi package so that we can properly test.
