### ISSUE TITLE
1.3.2: pytest if failing

### ISSUE THREAD

**Issue by kloczek** [box/genty#53]
Lokksk like it is some issue on usimg latest pytest.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-genty-1.3.2-12.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-genty-1.3.2-12.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -vvv
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/tkloczko/rpmbuild/BUILD/genty-1.3.2
collected 94 items

test/test_example.py::ExampleTests::test_dataprovider_with_no_dataset_no_dataset PASSED                                                                              [  1%]
test/test_example.py::ExampleTests::test_example_of_composing_datasets('first') PASSED                                                                               [  2%]
test/test_example.py::ExampleTests::test_example_of_composing_datasets('second') PASSED                                                                              [  3%]
test/test_example.py::ExampleTests::test_example_of_composing_datasets('third') PASSED                                                                               [  4%]
test/test_example.py::ExampleTests::test_example_of_composing_datasets(10) PASSED                                                                                    [  5%]
test/test_example.py::ExampleTests::test_example_of_composing_datasets(100) PASSED                                                                                   [  6%]
test/test_example.py::ExampleTests::test_example_of_datasets_with_kwargs('first', 'second', 'third') PASSED                                                          [  7%]
test/test_example.py::ExampleTests::test_example_of_datasets_with_kwargs('first', second_value='second', third_value='third') PASSED                                 [  8%]
test/test_example.py::ExampleTests::test_example_of_multiple_parameter_datasets(False, False) PASSED                                                                 [  9%]
test/test_example.py::ExampleTests::test_example_of_multiple_parameter_datasets(False, True) PASSED                                                                  [ 10%]
test/test_example.py::ExampleTests::test_example_of_multiple_parameter_datasets(True, False) PASSED                                                                  [ 11%]
test/test_example.py::ExampleTests::test_example_of_multiple_parameter_datasets(True, True) PASSED                                                                   [ 12%]
test/test_example.py::ExampleTests::test_example_of_named_datasets(another_test_case) PASSED                                                                         [ 13%]
test/test_example.py::ExampleTests::test_example_of_named_datasets(some_test_case) PASSED                                                                            [ 14%]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/runner.py", line 108, in pytest_runtest_protocol
INTERNALERROR>     ihook.pytest_runtest_logstart(nodeid=item.nodeid, location=item.location)
INTERNALERROR>   File "/usr/lib64/python3.8/functools.py", line 967, in __get__
INTERNALERROR>     val = self.func(instance)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/nodes.py", line 587, in location
INTERNALERROR>     location = self.reportinfo()
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/python.py", line 340, in reportinfo
INTERNALERROR>     fspath, lineno = getfslineno(obj)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/_code/code.py", line 1194, in getfslineno
INTERNALERROR>     obj = get_real_func(obj)
INTERNALERROR>   File "/usr/lib/python3.8/site-packages/_pytest/compat.py", line 271, in get_real_func
INTERNALERROR>     raise ValueError(
INTERNALERROR> ValueError: could not find real function of <function ExampleTests.test_example_of_repeat at 0x7f93ada3c280>
INTERNALERROR> stopped at <function ExampleTests.test_example_of_repeat at 0x7f93ada3c280>

============================================================================ 14 passed in 0.14s ============================================================================
```

**Comment by kloczek** [comment]
Sorry I've already reported that I've reported that in https://github.com/pytest-dev/pytest/issues/9030 :/

**Comment by kloczek** [comment]
Unit which meeses with pytest is `test/test_example.py::ExampleTests::test_example_of_repeat`.
After deselecting it:
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-genty-1.3.2-12.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-genty-1.3.2-12.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --deselect test/test_example.py::ExampleTests::test_example_of_repeat
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/genty-1.3.2
collected 94 items / 22 deselected / 72 selected

test/test_example.py ....................                                                                                                                            [ 27%]
test/test_genty.py ........................                                                                                                                          [ 61%]
test/test_genty_args.py ............                                                                                                                                 [ 77%]
test/test_genty_dataset.py ............                                                                                                                              [ 94%]
test/test_genty_repeat.py ....                                                                                                                                       [100%]

==================================================================== 72 passed, 22 deselected in 0.22s =====================================================================
```

**Comment by kloczek** [comment]
Closing.
I manage to remove using genty.
